download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/geerlingguy-php_roles-3.0.0.tar.gz
format_version: 1.0.0
name: php_roles
namespace: geerlingguy
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/geerlingguy/php_roles/versions/3.0.0/
